# Generated by Django 5.2.12 on 2026-03-26 05:42

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200)),
                ('content', models.TextField(help_text='Content of the blog post')),
                ('author', models.CharField(default='Anonymous', help_text='Author of the blog post', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'), models.Index(fields=['author'], name='posts_author_8275b2_idx')],
            },
        ),
    ]
